[package]
name = "rust_gba"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.4.4"
nalgebra = "0.32.3"
wgpu = "0.18.0"
winit = "0.29.4"
